"""
Central registry of FRED series metadata: human-readable names, units,
categories, filenames, and risk thresholds used for color-coding.

Risk thresholds are (low, high) tuples where None means unbounded.
`risk_basis` controls which value is scored: "level", "yoy", or "mom_change".
`higher_is_bad` is informational only (thresholds encode direction directly).
"""

REGISTRY = {
    # ── Inflation ──────────────────────────────────────────────────────────
    "CPIAUCSL": {
        "name": "CPI: All Items",
        "short_name": "CPI",
        "description": "Consumer Price Index for All Urban Consumers: All Items",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_all_items.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "notes": "Headline CPI including food and energy.",
    },
    "CPILFESL": {
        "name": "Core CPI (ex Food & Energy)",
        "short_name": "Core CPI",
        "description": "CPI for All Urban Consumers: All Items Less Food and Energy",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_core.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "notes": "Strips volatile food and energy; often considered a better trend signal.",
    },
    "PCEPILFE": {
        "name": "Core PCE Price Index",
        "short_name": "Core PCE",
        "description": "PCE Price Index Excluding Food and Energy — the Fed's preferred inflation gauge",
        "units": "Index (2017=100)",
        "category": "inflation",
        "filename": "pce_core.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "notes": "The FOMC's primary inflation target is 2% Core PCE. More current than CPI (~4 week lag vs BLS); tends to run 0.3–0.5% below Core CPI.",
    },
    # ── Money Supply ───────────────────────────────────────────────────────
    "M1SL": {
        "name": "M1 Money Supply",
        "short_name": "M1",
        "description": "M1 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m1.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "Currency, demand deposits, traveler's checks.",
    },
    "M2SL": {
        "name": "M2 Money Supply",
        "short_name": "M2",
        "description": "M2 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "Broad money: M1 plus savings, money market accounts, small CDs.",
    },
    "M2REAL": {
        "name": "Real M2 Money Supply",
        "short_name": "Real M2",
        "description": "Real M2 Money Stock (inflation-adjusted)",
        "units": "Billions of 1982–84 Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2_real.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        # Contraction (strongly negative YoY) is the concern
        "risk_thresholds": {"green": (-2, None), "yellow": (-6, -2), "red": (None, -6)},
        "higher_is_bad": False,
        "notes": "Inflation-adjusted M2. Persistent real contraction signals tightening conditions.",
    },
    # ── Volatility & Rates ─────────────────────────────────────────────────
    "VIXCLS": {
        "name": "CBOE Volatility Index",
        "short_name": "VIX",
        "description": "CBOE Volatility Index — implied 30-day S&P 500 volatility",
        "units": "Index Points",
        "category": "markets",
        "filename": "vix_volatility.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "notes": "VIX above 30 has historically coincided with elevated market stress.",
    },
    "DGS10": {
        "name": "10-Year Treasury Yield (Daily)",
        "short_name": "10Y Yield",
        "description": "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_daily.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "notes": "Benchmark long-term rate. Rapid rises increase debt service burden at elevated debt/GDP.",
    },
    "GS10": {
        "name": "10-Year Treasury Yield (Monthly)",
        "short_name": "10Y Yield (Mo.)",
        "description": "Market Yield on 10-Year Treasury Securities, Monthly Average",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_monthly.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "notes": "Monthly average 10-year yield; aligns well with other monthly macro series.",
    },
    # ── Financial Stress ───────────────────────────────────────────────────
    "SUBLPDRCSN": {
        "name": "CRE Lending Standards (SLOOS)",
        "short_name": "CRE Lending Stds",
        "description": "Net % of Domestic Banks Tightening Standards for CRE Loans (Nonfarm Nonresidential)",
        "units": "Percent (Net)",
        "category": "financial_stress",
        "filename": "cre_lending_standards.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 10), "yellow": (10, 40), "red": (40, None)},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "SLOOS CRE-specific tightening > 40% historically precedes CRE credit contraction by 2-4 quarters. More timely than delinquency data.",
    },
    # ── Fiscal ─────────────────────────────────────────────────────────────
    "GFDEGDQ188S": {
        "name": "Federal Debt (% of GDP)",
        "short_name": "Debt/GDP",
        "description": "Federal Debt: Total Public Debt as Percent of Gross Domestic Product",
        "units": "Percent of GDP",
        "category": "fiscal",
        "filename": "federal_debt_pct_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 80), "yellow": (80, 120), "red": (120, None)},
        "higher_is_bad": True,
        "notes": "Higher debt/GDP reduces fiscal flexibility, especially as interest rates rise.",
    },
    "GFDEBTN": {
        "name": "Federal Debt Outstanding (Monthly)",
        "short_name": "Federal Debt $B",
        "description": "Federal Debt: Total Public Debt in Billions of Dollars (Monthly)",
        "units": "Billions of Dollars",
        "category": "fiscal",
        "filename": "federal_debt_total.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 25000), "yellow": (25000, 35000), "red": (35000, None)},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "Monthly total public debt in billions. More timely than quarterly Debt/GDP ratio.",
    },
    # ── Market Valuation (Shiller / Yale) ─────────────────────────────────
    "SP500_PE": {
        "name": "S&P 500 Trailing P/E",
        "short_name": "S&P P/E",
        "description": "S&P 500 Trailing Price-to-Earnings Ratio (Price / TTM Earnings)",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_pe_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 27), "red": (27, None)},
        "higher_is_bad": True,
        "notes": "Trailing P/E from Shiller's dataset. Historical average ~16; elevated readings have historically preceded lower forward returns.",
    },
    "SP500_CAPE": {
        "name": "S&P 500 CAPE (Shiller P/E)",
        "short_name": "CAPE",
        "description": "Cyclically Adjusted Price-to-Earnings Ratio using 10-year real earnings average",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_cape.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "notes": "Shiller CAPE (PE10). Historical mean ~17. Readings above 30 have historically preceded decade-long below-average real returns.",
    },
    # ── Labor Market ───────────────────────────────────────────────────────
    "UNRATE": {
        "name": "Unemployment Rate",
        "short_name": "Unemployment",
        "description": "Unemployment Rate, Seasonally Adjusted (U-3)",
        "units": "Percent",
        "category": "labor",
        "filename": "unemployment_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 4.5), "yellow": (4.5, 6.0), "red": (6.0, None)},
        "higher_is_bad": True,
        "notes": "U-3 unemployment. Rising trend often matters as much as the absolute level.",
    },
    "EMRATIO": {
        "name": "Employment-Population Ratio",
        "short_name": "Emp/Pop Ratio",
        "description": "Employment-Population Ratio, Civilian Non-Institutional Population",
        "units": "Percent",
        "category": "labor",
        "filename": "employment_population_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (60, None), "yellow": (57, 60), "red": (None, 57)},
        "higher_is_bad": False,
        "notes": "Broader utilization measure; not distorted by participation rate changes.",
    },
    "CIVPART": {
        "name": "Labor Force Participation Rate",
        "short_name": "LFPR",
        "description": "Civilian Labor Force Participation Rate",
        "units": "Percent",
        "category": "labor",
        "filename": "labor_force_participation.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (63, None), "yellow": (61, 63), "red": (None, 61)},
        "higher_is_bad": False,
        "notes": "Secular decline since 2000 reflects demographics; cyclical drops signal labor weakness.",
    },
    "PAYEMS": {
        "name": "Nonfarm Payrolls",
        "short_name": "Payrolls",
        "description": "All Employees, Total Nonfarm Payrolls, Seasonally Adjusted",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "nonfarm_payrolls.csv",
        "frequency": "Monthly",
        "risk_basis": "mom_change",
        "risk_thresholds": {"green": (100, None), "yellow": (0, 100), "red": (None, 0)},
        "higher_is_bad": False,
        "notes": "Monthly payroll additions. Below 100K signals softening; negative signals contraction.",
    },
    "ICSA": {
        "name": "Initial Jobless Claims",
        "short_name": "Init. Claims",
        "description": "Initial Claims for Unemployment Insurance (Weekly, Seasonally Adjusted)",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "initial_jobless_claims.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 250), "yellow": (250, 350), "red": (350, None)},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "Weekly leading labor indicator — rises before unemployment rate. Green: <250K; yellow: 250-350K; red: >350K.",
    },
    "PSAVERT": {
        "name": "Personal Saving Rate",
        "short_name": "Savings Rate",
        "description": "Personal Saving as a Percentage of Disposable Personal Income",
        "units": "Percent",
        "category": "labor",
        "filename": "personal_savings_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (7, None), "yellow": (4, 7), "red": (None, 4)},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Low savings rate means households have less buffer against income shocks. Historically ~7-10% pre-2000.",
    },
    "INDPRO": {
        "name": "Industrial Production Index",
        "short_name": "Indust. Production",
        "description": "Industrial Production: Total Index (2017=100, Seasonally Adjusted)",
        "units": "Index (2017=100)",
        "category": "labor",
        "filename": "industrial_production.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (1.0, None), "yellow": (-1.0, 1.0), "red": (None, -1.0)},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Real-economy output measure; leads GDP. YoY contraction is a recession-consistent signal.",
    },
    "USSLIND": {
        "name": "Leading Economic Index",
        "short_name": "LEI",
        "description": "Conference Board Leading Economic Index — composite of 10 leading indicators",
        "units": "Index (2016=100)",
        "category": "labor",
        "filename": "leading_economic_index.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (0, None), "yellow": (-5, 0), "red": (None, -5)},
        "higher_is_bad": False,
        "show_in_summary": True,
        "notes": "Persistent 6-month negative readings have preceded every US recession since 1960. More reliable than any single indicator.",
    },
    # ── Liquidity & Funding Stress ─────────────────────────────────────────
    "STLFSI4": {
        "name": "Financial Stress Index (St. Louis Fed)",
        "short_name": "FSI",
        "description": "St. Louis Fed Financial Stress Index — measures degree of financial stress in markets",
        "units": "Index",
        "category": "liquidity_stress",
        "filename": "stlfsi4.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 1.5), "red": (1.5, None)},
        "higher_is_bad": True,
        "notes": "Index centered at 0. Negative = below-average stress; positive = above-average. Readings above 1.5 indicate significant systemic stress.",
    },
    "DCPF3M": {
        "name": "3-Month AA Financial CP Rate",
        "short_name": "3M CP Rate",
        "description": "3-Month AA Financial Commercial Paper Rate (Discount Basis) — short-term unsecured bank borrowing cost",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "cp_3m_financial.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.5), "yellow": (5.5, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "Supporting series for CP-Treasury spread. Raw level reflects both policy rate and credit premium.",
    },
    "DGS3MO": {
        "name": "3-Month Treasury Rate",
        "short_name": "3M Treasury",
        "description": "3-Month Treasury Constant Maturity Rate — the short-term risk-free benchmark",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "treasury_3m.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.5), "yellow": (5.5, 7.0), "red": (7.0, None)},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Supporting series for CP-Treasury spread computation.",
    },
    "SOFR": {
        "name": "Secured Overnight Financing Rate",
        "short_name": "SOFR",
        "description": "Secured Overnight Financing Rate — daily rate for overnight Treasury-collateralized repo transactions",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "sofr_rate.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "LIBOR replacement rate since 2022. In isolation tracks Fed Funds rate; dislocations vs FEDFUNDS signal repo funding stress.",
    },
    "RRPONTSYD": {
        "name": "Fed Overnight Reverse Repo (RRP)",
        "short_name": "Reverse Repo",
        "description": "Overnight Reverse Repurchase Agreements: Treasury Securities Sold by Federal Reserve in Billions",
        "units": "Billions of Dollars",
        "category": "liquidity_stress",
        "filename": "rrp_usage.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (500, None), "yellow": (100, 500), "red": (None, 100)},
        "higher_is_bad": False,
        "notes": "Usage of the Fed's overnight RRP facility. High levels indicate excess reserves; rapid drawdown toward zero signals liquidity leaving the system.",
    },
    # ── Credit Market Functionality ────────────────────────────────────────
    "BAMLH0A0HYM2": {
        "name": "High Yield OAS (ICE BofA)",
        "short_name": "HY Spread",
        "description": "ICE BofA US High Yield Index Option-Adjusted Spread — credit risk premium demanded by HY bond market",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "hy_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 4.0), "yellow": (4.0, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "notes": "Credit spread in percent (400 bps = 4.0%). Pre-crisis normal: 3-4%. Persistent widening above 400 bps signals refinancing stress; above 700 bps indicates systemic credit deterioration.",
    },
    "DRCCLACBS": {
        "name": "Credit Card Loan Delinquency Rate",
        "short_name": "CC Delinquency",
        "description": "Delinquency Rate on Credit Card Loans at All Commercial Banks",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "cc_delinquency_rate.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 3.0), "yellow": (3.0, 5.0), "red": (5.0, None)},
        "higher_is_bad": True,
        "notes": "Quarterly H.8 release. Measures consumer credit health; peaked at ~6.8% in 2009. More timely within quarter than CRE data.",
    },
    "BAMLC0A0CM": {
        "name": "Investment Grade OAS (ICE BofA)",
        "short_name": "IG Spread",
        "description": "ICE BofA US Corporate Master Option-Adjusted Spread — investment grade credit premium",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "ig_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.5), "yellow": (1.5, 2.5), "red": (2.5, None)},
        "higher_is_bad": True,
        "notes": "IG corporate spread in percent. Normal range: 0.8-1.5%. Widening above 2.5% signals credit tightening reaching investment-grade issuers.",
    },
    # ── Policy Constraints ─────────────────────────────────────────────────
    "WALCL": {
        "name": "Fed Balance Sheet (Total Assets)",
        "short_name": "Fed Assets",
        "description": "Federal Reserve: Total Assets (Less Eliminations from Consolidation), Wednesday Level",
        "units": "Millions of Dollars",
        "category": "policy_flex",
        "filename": "fed_balance_sheet.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Fed balance sheet size in millions. Tracks QE expansion and QT reduction. Context indicator — no simple threshold; shown as % of GDP for comparability.",
    },
    "FEDFUNDS": {
        "name": "Federal Funds Effective Rate",
        "short_name": "Fed Funds",
        "description": "Federal Funds Effective Rate — overnight interbank lending rate set by FOMC",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "fed_funds_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "The policy rate. High nominal rates are not inherently bad; the real rate (FEDFUNDS minus core CPI) is more informative for evaluating policy stance.",
    },
    "T5YIE": {
        "name": "5-Year Breakeven Inflation Rate",
        "short_name": "5Y BEI",
        "description": "5-Year Breakeven Inflation Rate — market-implied 5-year average inflation expectations",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "inflation_exp_5y.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 3.2), "red": (3.2, None)},
        "higher_is_bad": True,
        "notes": "Derived from TIPS breakevens. Persistent readings above 3% signal inflation expectations unanchoring, which constrains the Fed's ability to ease policy.",
    },
    "T10YIE": {
        "name": "10-Year Breakeven Inflation Rate",
        "short_name": "10Y BEI",
        "description": "10-Year Breakeven Inflation Rate — market-implied long-run inflation expectations",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "inflation_exp_10y.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 3.0), "red": (3.0, None)},
        "higher_is_bad": True,
        "notes": "Long-run inflation expectations from TIPS market. Unanchoring above 3% would severely constrain the Fed's ability to respond to economic weakness.",
    },
    # ── Fiscal Maneuverability (raw components — not shown as standalone KPIs) ──
    "A091RC1Q027SBEA": {
        "name": "Federal Interest Payments",
        "short_name": "Interest Pmts",
        "description": "Government, Federal: Interest Payments (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "policy_flex",
        "filename": "federal_interest_payments.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "Numerator for debt service burden ratio. Combined with W006RC1Q027SBEA to yield interest/receipts %.",
    },
    "W006RC1Q027SBEA": {
        "name": "Federal Current Receipts",
        "short_name": "Fed Receipts",
        "description": "Government, Federal: Current Receipts (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "policy_flex",
        "filename": "federal_current_receipts.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Denominator for debt service burden ratio.",
    },
    "GDP": {
        "name": "Nominal GDP",
        "short_name": "GDP",
        "description": "Gross Domestic Product, Nominal (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "fiscal",
        "filename": "nominal_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "show_in_summary": False,
        "notes": "Nominal GDP for computing balance sheet % of GDP and similar ratios.",
    },
    # ── Financial Conditions Index ─────────────────────────────────────────
    "NFCI": {
        "name": "National Financial Conditions Index",
        "short_name": "NFCI",
        "description": "Chicago Fed National Financial Conditions Index — weekly measure of U.S. financial conditions",
        "units": "Index",
        "category": "liquidity_stress",
        "filename": "nfci.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 0.7), "red": (0.7, None)},
        "higher_is_bad": True,
        "notes": "Index centered at 0 (average conditions, 1971 onward). Positive = tighter than average; negative = looser. Combines 105 financial indicators across risk, credit, and leverage.",
    },
    "NFCICREDIT": {
        "name": "NFCI Credit Subindex",
        "short_name": "NFCI Credit",
        "description": "Chicago Fed NFCI: Credit Subindex — measures tightness of credit conditions specifically",
        "units": "Index",
        "category": "credit_markets",
        "filename": "nfci_credit.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 0.7), "red": (0.7, None)},
        "higher_is_bad": True,
        "notes": "Credit-specific sub-index of NFCI. Isolates the credit channel from broader financial conditions.",
    },
    # ── Yield Curve ───────────────────────────────────────────────────────
    "T10Y2Y": {
        "name": "Yield Curve Spread (10Y − 2Y)",
        "short_name": "Yield Curve",
        "description": "10-Year Treasury Yield minus 2-Year Treasury Yield",
        "units": "Percent",
        "category": "rates",
        "filename": "yield_curve_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (0.5, None), "yellow": (0.0, 0.5), "red": (None, 0.0)},
        "higher_is_bad": False,
        "notes": "Inverted curve (negative) has preceded every US recession since 1970. Green = normal slope; yellow = flat; red = inverted.",
    },
    # ── Bank Lending Standards ─────────────────────────────────────────────
    "DRTSCILM": {
        "name": "Bank Lending Standards (C&I Loans)",
        "short_name": "Lending Stds",
        "description": "Net % of Domestic Banks Tightening Standards for C&I Loans, Large & Medium Firms",
        "units": "Percent (Net)",
        "category": "credit_markets",
        "filename": "bank_lending_standards.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 10), "yellow": (10, 40), "red": (40, None)},
        "higher_is_bad": True,
        "notes": "SLOOS survey. Positive = net tightening; negative = net loosening. Tightening above 40% has historically preceded credit contractions.",
    },
    # ── Recession Probability ──────────────────────────────────────────────
    "RECPROUSM156N": {
        "name": "Recession Probability (NY Fed, 12-Month)",
        "short_name": "Rec. Probability",
        "description": "NY Fed Probability of US Recession Predicted by Treasury Spread, 12 Months Ahead",
        "units": "Percent",
        "category": "financial_stress",
        "filename": "recession_probability.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 15), "yellow": (15, 40), "red": (40, None)},
        "higher_is_bad": True,
        "notes": "NY Fed probit model using the 3-month / 10-year yield spread. Readings above 30% have historically been reliable recession signals.",
    },
    # ── Housing ───────────────────────────────────────────────────────────
    "MORTGAGE30US": {
        "name": "30-Year Fixed Mortgage Rate",
        "short_name": "Mortgage Rate",
        "description": "30-Year Fixed Rate Mortgage Average in the United States (Freddie Mac PMMS)",
        "units": "Percent",
        "category": "housing",
        "filename": "mortgage_rate_30y.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "notes": "Primary Mortgage Market Survey. Higher rates directly reduce housing affordability and suppress transaction volume and starts.",
    },
    "HOUST": {
        "name": "Housing Starts (Total)",
        "short_name": "Housing Starts",
        "description": "Housing Starts: Total New Privately Owned Housing Units Started, SAAR",
        "units": "Thousands of Units",
        "category": "housing",
        "filename": "housing_starts.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (1300, None), "yellow": (900, 1300), "red": (None, 900)},
        "higher_is_bad": False,
        "notes": "Leading indicator for construction employment and materials demand. Very sensitive to mortgage rates.",
    },
    "CSUSHPINSA": {
        "name": "Case-Shiller Home Price Index",
        "short_name": "Home Prices",
        "description": "S&P CoreLogic Case-Shiller U.S. National Home Price Index (NSA)",
        "units": "Index (Jan 2000 = 100)",
        "category": "housing",
        "filename": "case_shiller_hpi.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "3-month smoothed repeat-sales index. Published with ~2-month lag. YoY above 8% signals affordability stress.",
    },
    # ── Dollar ────────────────────────────────────────────────────────────
    "DTWEXBGS": {
        "name": "Broad U.S. Dollar Index",
        "short_name": "Dollar Index",
        "description": "Nominal Broad U.S. Dollar Index (Goods, Trade-Weighted vs. 26 major currencies)",
        "units": "Index (Jan 2006 = 100)",
        "category": "markets",
        "filename": "dollar_index.csv",
        "frequency": "Weekly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "Broad trade-weighted dollar. Rapid appreciation (>8% YoY) tightens global financial conditions, pressures EM debt, and weighs on US multinationals.",
    },
    # ── Recession Reference (not shown as a KPI) ──────────────────────────
    "USREC": {
        "name": "NBER Recession Indicator",
        "short_name": "Recession",
        "description": "NBER Based Recession Indicators for the United States (1=Recession, 0=Expansion)",
        "units": "Binary",
        "category": "labor",
        "filename": "us_recession.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": True,
        "show_in_summary": False,
        "notes": "Used exclusively for recession shading on charts.",
    },
}

# Display labels for each category group
CATEGORY_LABELS = {
    "inflation":       "Inflation & Prices",
    "money_supply":    "Money Supply",
    "markets":         "Markets",
    "rates":           "Interest Rates",
    "financial_stress":"Financial Stress",
    "fiscal":          "Fiscal Health",
    "labor":           "Labor Market",
    "valuation":       "Market Valuation",
    "housing":         "Housing Market",
    # System resilience categories
    "liquidity_stress": "Liquidity & Funding Stress",
    "credit_markets":   "Credit Market Functionality",
    "policy_flex":      "Policy Constraints",
}

# Ordered list for display
CATEGORY_ORDER = [
    "inflation", "labor", "valuation", "markets", "rates",
    "financial_stress", "fiscal", "money_supply", "housing",
    "liquidity_stress", "credit_markets", "policy_flex",
]
