"""
Central registry of FRED series metadata: human-readable names, units,
categories, filenames, and risk thresholds used for color-coding.

Risk thresholds are (low, high) tuples where None means unbounded.
`risk_basis` controls which value is scored: "level", "yoy", or "mom_change".
`higher_is_bad` is informational only (thresholds encode direction directly).
"""

REGISTRY = {
    # ── Inflation ──────────────────────────────────────────────────────────
    "CPIAUCSL": {
        "name": "CPI: All Items",
        "short_name": "CPI",
        "description": "Consumer Price Index for All Urban Consumers: All Items",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_all_items.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "notes": "Headline CPI including food and energy.",
    },
    "CPILFESL": {
        "name": "Core CPI (ex Food & Energy)",
        "short_name": "Core CPI",
        "description": "CPI for All Urban Consumers: All Items Less Food and Energy",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_core.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "notes": "Strips volatile food and energy; often considered a better trend signal.",
    },
    "FPCPITOTLZGUSA": {
        "name": "Inflation Rate (Annual)",
        "short_name": "Inflation",
        "description": "Inflation, Consumer Prices for the United States",
        "units": "% Per Year",
        "category": "inflation",
        "filename": "inflation_annual_pct.csv",
        "frequency": "Annual",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "notes": "World Bank annual inflation series.",
    },
    # ── Money Supply ───────────────────────────────────────────────────────
    "M1SL": {
        "name": "M1 Money Supply",
        "short_name": "M1",
        "description": "M1 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m1.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "Currency, demand deposits, traveler's checks.",
    },
    "M2SL": {
        "name": "M2 Money Supply",
        "short_name": "M2",
        "description": "M2 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "notes": "Broad money: M1 plus savings, money market accounts, small CDs.",
    },
    "M2REAL": {
        "name": "Real M2 Money Supply",
        "short_name": "Real M2",
        "description": "Real M2 Money Stock (inflation-adjusted)",
        "units": "Billions of 1982–84 Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2_real.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        # Contraction (strongly negative YoY) is the concern
        "risk_thresholds": {"green": (-2, None), "yellow": (-6, -2), "red": (None, -6)},
        "higher_is_bad": False,
        "notes": "Inflation-adjusted M2. Persistent real contraction signals tightening conditions.",
    },
    # ── Volatility & Rates ─────────────────────────────────────────────────
    "VIXCLS": {
        "name": "CBOE Volatility Index",
        "short_name": "VIX",
        "description": "CBOE Volatility Index — implied 30-day S&P 500 volatility",
        "units": "Index Points",
        "category": "markets",
        "filename": "vix_volatility.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "notes": "VIX above 30 has historically coincided with elevated market stress.",
    },
    "DGS10": {
        "name": "10-Year Treasury Yield (Daily)",
        "short_name": "10Y Yield",
        "description": "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_daily.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "notes": "Benchmark long-term rate. Rapid rises increase debt service burden at elevated debt/GDP.",
    },
    "GS10": {
        "name": "10-Year Treasury Yield (Monthly)",
        "short_name": "10Y Yield (Mo.)",
        "description": "Market Yield on 10-Year Treasury Securities, Monthly Average",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_monthly.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "notes": "Monthly average 10-year yield; aligns well with other monthly macro series.",
    },
    # ── Financial Stress ───────────────────────────────────────────────────
    "DRCRELEXFACBS": {
        "name": "CRE Loan Delinquency Rate",
        "short_name": "CRE Delinquency",
        "description": "Delinquency Rate on Commercial Real Estate Loans, Excluding Farmland",
        "units": "Percent",
        "category": "financial_stress",
        "filename": "cre_delinquency_rate.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.5), "yellow": (1.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "notes": "Rising CRE delinquencies signal stress in commercial lending — often a leading indicator.",
    },
    # ── Fiscal ─────────────────────────────────────────────────────────────
    "GFDEGDQ188S": {
        "name": "Federal Debt (% of GDP)",
        "short_name": "Debt/GDP",
        "description": "Federal Debt: Total Public Debt as Percent of Gross Domestic Product",
        "units": "Percent of GDP",
        "category": "fiscal",
        "filename": "federal_debt_pct_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 80), "yellow": (80, 120), "red": (120, None)},
        "higher_is_bad": True,
        "notes": "Higher debt/GDP reduces fiscal flexibility, especially as interest rates rise.",
    },
    # ── Market Valuation (Shiller / Yale) ─────────────────────────────────
    "SP500_PE": {
        "name": "S&P 500 Trailing P/E",
        "short_name": "S&P P/E",
        "description": "S&P 500 Trailing Price-to-Earnings Ratio (Price / TTM Earnings)",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_pe_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 27), "red": (27, None)},
        "higher_is_bad": True,
        "notes": "Trailing P/E from Shiller's dataset. Historical average ~16; elevated readings have historically preceded lower forward returns.",
    },
    "SP500_CAPE": {
        "name": "S&P 500 CAPE (Shiller P/E)",
        "short_name": "CAPE",
        "description": "Cyclically Adjusted Price-to-Earnings Ratio using 10-year real earnings average",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_cape.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "notes": "Shiller CAPE (PE10). Historical mean ~17. Readings above 30 have historically preceded decade-long below-average real returns.",
    },
    # ── Labor Market ───────────────────────────────────────────────────────
    "UNRATE": {
        "name": "Unemployment Rate",
        "short_name": "Unemployment",
        "description": "Unemployment Rate, Seasonally Adjusted (U-3)",
        "units": "Percent",
        "category": "labor",
        "filename": "unemployment_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 4.5), "yellow": (4.5, 6.0), "red": (6.0, None)},
        "higher_is_bad": True,
        "notes": "U-3 unemployment. Rising trend often matters as much as the absolute level.",
    },
    "EMRATIO": {
        "name": "Employment-Population Ratio",
        "short_name": "Emp/Pop Ratio",
        "description": "Employment-Population Ratio, Civilian Non-Institutional Population",
        "units": "Percent",
        "category": "labor",
        "filename": "employment_population_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (60, None), "yellow": (57, 60), "red": (None, 57)},
        "higher_is_bad": False,
        "notes": "Broader utilization measure; not distorted by participation rate changes.",
    },
    "CIVPART": {
        "name": "Labor Force Participation Rate",
        "short_name": "LFPR",
        "description": "Civilian Labor Force Participation Rate",
        "units": "Percent",
        "category": "labor",
        "filename": "labor_force_participation.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (63, None), "yellow": (61, 63), "red": (None, 61)},
        "higher_is_bad": False,
        "notes": "Secular decline since 2000 reflects demographics; cyclical drops signal labor weakness.",
    },
    "PAYEMS": {
        "name": "Nonfarm Payrolls",
        "short_name": "Payrolls",
        "description": "All Employees, Total Nonfarm Payrolls, Seasonally Adjusted",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "nonfarm_payrolls.csv",
        "frequency": "Monthly",
        "risk_basis": "mom_change",
        "risk_thresholds": {"green": (100, None), "yellow": (0, 100), "red": (None, 0)},
        "higher_is_bad": False,
        "notes": "Monthly payroll additions. Below 100K signals softening; negative signals contraction.",
    },
}

# Display labels for each category group
CATEGORY_LABELS = {
    "inflation": "Inflation & Prices",
    "money_supply": "Money Supply",
    "markets": "Markets",
    "rates": "Interest Rates",
    "financial_stress": "Financial Stress",
    "fiscal": "Fiscal Health",
    "labor": "Labor Market",
    "valuation": "Market Valuation",
}

# Ordered list for display
CATEGORY_ORDER = ["inflation", "labor", "valuation", "markets", "rates", "financial_stress", "fiscal", "money_supply"]
