"""
Central registry of FRED series metadata: human-readable names, units,
categories, filenames, and risk thresholds used for color-coding.

Risk thresholds are (low, high) tuples where None means unbounded.
`risk_basis` controls which value is scored: "level", "yoy", or "mom_change".
`higher_is_bad` is informational only (thresholds encode direction directly).

Scoring methodology fields
───────────────────────────
normalization_method
    "fixed_thresholds"   – hardcoded (lo, hi) pairs, expert / literature-calibrated
    "percentile"         – current value ranked against calibration-window distribution
                           green < 75th pctile, yellow 75–90th, red ≥ 90th
                           (reversed for higher_is_bad=False)
    "zscore"             – z-score vs. rolling calibration-window distribution
                           |z| < 1 → green, 1–2 → yellow, ≥ 2 → red
    "standardized_index" – index already centered at 0 (STLFSI4, NFCI, NFCICREDIT);
                           uses fixed_thresholds but thresholds reflect known index units

calibration_window_years
    Look-back window (years) used for percentile / zscore calibration.
    For fixed-threshold series this documents the historical period used to
    set thresholds, not an active computation parameter.

threshold_rationale
    One-sentence justification grounding thresholds in literature or statistics.

predictive_reliability  (0.0 – 1.0)
    Expert-assigned signal reliability weight, used in confidence_score().
    Draws on Estrella & Mishkin (1998), Conference Board LEI methodology,
    NBER recession research, and Fed SLOOS academic literature.

revision_risk  ("low" | "medium" | "high")
    Penalty for data series subject to large initial-release revisions,
    used in confidence_score().
"""

REGISTRY = {
    # ── Inflation ──────────────────────────────────────────────────────────
    "CPIAUCSL": {
        "name": "CPI: All Items",
        "short_name": "CPI",
        "description": "Consumer Price Index for All Urban Consumers: All Items",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_all_items.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Fed 2% target defines green; >4.5% YoY historically required restrictive monetary policy. Yellow 2.5–4.5% = above target but not extreme.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "notes": "Headline CPI including food and energy.",
    },
    "CPILFESL": {
        "name": "Core CPI (ex Food & Energy)",
        "short_name": "Core CPI",
        "description": "CPI for All Urban Consumers: All Items Less Food and Energy",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_core.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Fed 2% target; core strips food/energy volatility. Persistent core >4% signals structural inflation requiring sustained tightening.",
        "predictive_reliability": 0.80,
        "revision_risk": "medium",
        "notes": "Strips volatile food and energy; often considered a better trend signal.",
    },
    "PCEPILFE": {
        "name": "Core PCE Price Index",
        "short_name": "Core PCE",
        "description": "PCE Price Index Excluding Food and Energy — the Fed's preferred inflation gauge",
        "units": "Index (2017=100)",
        "category": "inflation",
        "filename": "pce_core.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "FOMC 2% Core PCE target; thresholds mirror Core CPI adjusted for the typical 0.3–0.5pp CPI–PCE differential.",
        "predictive_reliability": 0.85,
        "revision_risk": "medium",
        "notes": "The FOMC's primary inflation target is 2% Core PCE. More current than CPI (~4 week lag vs BLS); tends to run 0.3–0.5% below Core CPI.",
    },
    # ── Money Supply ───────────────────────────────────────────────────────
    "M1SL": {
        "name": "M1 Money Supply",
        "short_name": "M1",
        "description": "M1 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m1.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. 20-year distribution; rapid M1 expansion has led inflation with variable lags. 2020 definitional change inflated YoY readings — use with caution.",
        "predictive_reliability": 0.40,
        "revision_risk": "low",
        "notes": "Currency, demand deposits, traveler's checks.",
    },
    "M2SL": {
        "name": "M2 Money Supply",
        "short_name": "M2",
        "description": "M2 Money Stock",
        "units": "Billions of Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile of 20-year distribution; M2 expansion historically led inflation by 12–18 months, though the relationship weakened post-2008.",
        "predictive_reliability": 0.45,
        "revision_risk": "low",
        "notes": "Broad money: M1 plus savings, money market accounts, small CDs.",
    },
    "M2REAL": {
        "name": "Real M2 Money Supply",
        "short_name": "Real M2",
        "description": "Real M2 Money Stock (inflation-adjusted)",
        "units": "Billions of 1982–84 Dollars",
        "category": "money_supply",
        "filename": "money_supply_m2_real.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        # Contraction (strongly negative YoY) is the concern
        "risk_thresholds": {"green": (-2, None), "yellow": (-6, -2), "red": (None, -6)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Real contraction is the primary risk signal; scored by percentile of post-2000 distribution (lower percentile = worse for higher_is_bad=False).",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "notes": "Inflation-adjusted M2. Persistent real contraction signals tightening conditions.",
    },
    # ── Volatility & Rates ─────────────────────────────────────────────────
    "VIXCLS": {
        "name": "CBOE Volatility Index",
        "short_name": "VIX",
        "description": "CBOE Volatility Index — implied 30-day S&P 500 volatility",
        "units": "Index Points",
        "category": "markets",
        "filename": "vix_volatility.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "VIX 20 ≈ 75th percentile, VIX 30 ≈ 90th percentile of post-1990 distribution — fixed thresholds coincide with well-established market-stress breakpoints.",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "VIX above 30 has historically coincided with elevated market stress.",
    },
    "DGS10": {
        "name": "10-Year Treasury Yield (Daily)",
        "short_name": "10Y Yield",
        "description": "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_daily.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile of post-1990 distribution; absolute level matters in context of debt/GDP — above-average rates raise refinancing burden non-linearly.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "notes": "Benchmark long-term rate. Rapid rises increase debt service burden at elevated debt/GDP.",
    },
    "GS10": {
        "name": "10-Year Treasury Yield (Monthly)",
        "short_name": "10Y Yield (Mo.)",
        "description": "Market Yield on 10-Year Treasury Securities, Monthly Average",
        "units": "Percent",
        "category": "rates",
        "filename": "treasury_yield_10y_monthly.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 6.5), "red": (6.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Same methodology as DGS10; monthly average used for long-term trend analysis aligned with other monthly macro series.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "notes": "Monthly average 10-year yield; aligns well with other monthly macro series.",
    },
    # ── Financial Stress ───────────────────────────────────────────────────
    "SUBLPDRCSN": {
        "name": "CRE Lending Standards (SLOOS)",
        "short_name": "CRE Lending Stds",
        "description": "Net % of Domestic Banks Tightening Standards for CRE Loans (Nonfarm Nonresidential)",
        "units": "Percent (Net)",
        "category": "financial_stress",
        "filename": "cre_lending_standards.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 10), "yellow": (10, 40), "red": (40, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": ">40% net tightening has historically preceded CRE credit contraction by 2–4 quarters (Fed SLOOS academic literature).",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "SLOOS CRE-specific tightening > 40% historically precedes CRE credit contraction by 2-4 quarters. More timely than delinquency data.",
    },
    # ── Fiscal ─────────────────────────────────────────────────────────────
    "GFDEGDQ188S": {
        "name": "Federal Debt (% of GDP)",
        "short_name": "Debt/GDP",
        "description": "Federal Debt: Total Public Debt as Percent of Gross Domestic Product",
        "units": "Percent of GDP",
        "category": "fiscal",
        "filename": "federal_debt_pct_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 80), "yellow": (80, 120), "red": (120, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "IMF Fiscal Monitor framework: 80% of GDP = elevated; 120%+ = high-risk trajectory for developed-market sovereign debt sustainability.",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "notes": "Higher debt/GDP reduces fiscal flexibility, especially as interest rates rise.",
    },
    "GFDEBTN": {
        "name": "Federal Debt Outstanding (Monthly)",
        "short_name": "Federal Debt $B",
        "description": "Federal Debt: Total Public Debt in Billions of Dollars (Monthly)",
        "units": "Billions of Dollars",
        "category": "fiscal",
        "filename": "federal_debt_total.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 25000), "yellow": (25000, 35000), "red": (35000, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Nominal levels benchmarked to current cycle; use Debt/GDP (GFDEGDQ188S) for cross-time comparability — this series is more timely.",
        "predictive_reliability": 0.45,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Monthly total public debt in billions. More timely than quarterly Debt/GDP ratio.",
    },
    # ── Market Valuation (Shiller / Yale) ─────────────────────────────────
    "SP500_PE": {
        "name": "S&P 500 Trailing P/E",
        "short_name": "S&P P/E",
        "description": "S&P 500 Trailing Price-to-Earnings Ratio (Price / TTM Earnings)",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_pe_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 27), "red": (27, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 30,
        "threshold_rationale": "Percentile vs. post-1950 distribution; historical mean ~16x. Poor recession predictor but reliable long-run return predictor.",
        "predictive_reliability": 0.55,
        "revision_risk": "high",
        "notes": "Trailing P/E from Shiller's dataset. Historical average ~16; elevated readings have historically preceded lower forward returns.",
    },
    "SP500_CAPE": {
        "name": "S&P 500 CAPE (Shiller P/E)",
        "short_name": "CAPE",
        "description": "Cyclically Adjusted Price-to-Earnings Ratio using 10-year real earnings average",
        "units": "Ratio",
        "category": "valuation",
        "filename": "sp500_cape.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 30), "red": (30, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Shiller (2000): CAPE above 25 = 'danger zone'; above 30 = peak territory historically associated with decade-long below-average real returns (1880–2025 calibration).",
        "predictive_reliability": 0.65,
        "revision_risk": "medium",
        "notes": "Shiller CAPE (PE10). Historical mean ~17. Readings above 30 have historically preceded decade-long below-average real returns.",
    },
    # ── Labor Market ───────────────────────────────────────────────────────
    "UNRATE": {
        "name": "Unemployment Rate",
        "short_name": "Unemployment",
        "description": "Unemployment Rate, Seasonally Adjusted (U-3)",
        "units": "Percent",
        "category": "labor",
        "filename": "unemployment_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 4.5), "yellow": (4.5, 6.0), "red": (6.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1990 distribution; rate-of-change (Sahm Rule: +0.5pp above 12-month low) matters as much as level. Rising trend is the primary risk signal.",
        "predictive_reliability": 0.85,
        "revision_risk": "medium",
        "notes": "U-3 unemployment. Rising trend often matters as much as the absolute level.",
    },
    "EMRATIO": {
        "name": "Employment-Population Ratio",
        "short_name": "Emp/Pop Ratio",
        "description": "Employment-Population Ratio, Civilian Non-Institutional Population",
        "units": "Percent",
        "category": "labor",
        "filename": "employment_population_ratio.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (60, None), "yellow": (57, 60), "red": (None, 57)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 distribution; not distorted by participation-rate cyclicality. Below ~59% historically aligns with labor market weakness.",
        "predictive_reliability": 0.70,
        "revision_risk": "low",
        "notes": "Broader utilization measure; not distorted by participation rate changes.",
    },
    "CIVPART": {
        "name": "Labor Force Participation Rate",
        "short_name": "LFPR",
        "description": "Civilian Labor Force Participation Rate",
        "units": "Percent",
        "category": "labor",
        "filename": "labor_force_participation.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (63, None), "yellow": (61, 63), "red": (None, 61)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 distribution; rolling window prevents false signals from the secular post-2000 demographic decline in participation.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "notes": "Secular decline since 2000 reflects demographics; cyclical drops signal labor weakness.",
    },
    "PAYEMS": {
        "name": "Nonfarm Payrolls",
        "short_name": "Payrolls",
        "description": "All Employees, Total Nonfarm Payrolls, Seasonally Adjusted",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "nonfarm_payrolls.csv",
        "frequency": "Monthly",
        "risk_basis": "mom_change",
        "risk_thresholds": {"green": (100, None), "yellow": (0, 100), "red": (None, 0)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Monthly additions percentile vs. post-1990 distribution; negative growth is universally adverse. Very high revision risk — first release often revised ±100K.",
        "predictive_reliability": 0.85,
        "revision_risk": "high",
        "notes": "Monthly payroll additions. Below 100K signals softening; negative signals contraction.",
    },
    "ICSA": {
        "name": "Initial Jobless Claims",
        "short_name": "Init. Claims",
        "description": "Initial Claims for Unemployment Insurance (Weekly, Seasonally Adjusted)",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "initial_jobless_claims.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 250), "yellow": (250, 350), "red": (350, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 distribution; leading labor indicator that rises before the unemployment rate. Weekly frequency with minimal revisions = high data confidence.",
        "predictive_reliability": 0.85,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Weekly leading labor indicator — rises before unemployment rate. Green: <250K; yellow: 250-350K; red: >350K.",
    },
    "PSAVERT": {
        "name": "Personal Saving Rate",
        "short_name": "Savings Rate",
        "description": "Personal Saving as a Percentage of Disposable Personal Income",
        "units": "Percent",
        "category": "labor",
        "filename": "personal_savings_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (7, None), "yellow": (4, 7), "red": (None, 4)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1990 distribution; low savings signals reduced household buffer against income shocks. Historically ~7–10% pre-2000.",
        "predictive_reliability": 0.60,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Low savings rate means households have less buffer against income shocks. Historically ~7-10% pre-2000.",
    },
    "INDPRO": {
        "name": "Industrial Production Index",
        "short_name": "Indust. Production",
        "description": "Industrial Production: Total Index (2017=100, Seasonally Adjusted)",
        "units": "Index (2017=100)",
        "category": "labor",
        "filename": "industrial_production.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (1.0, None), "yellow": (-1.0, 1.0), "red": (None, -1.0)},
        "higher_is_bad": False,
        "normalization_method": "zscore",
        "calibration_window_years": 30,
        "threshold_rationale": "Z-score vs. 30-year YoY distribution; consecutive negative readings define an industrial recession and have preceded every broad recession since 1970.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Real-economy output measure; leads GDP. YoY contraction is a recession-consistent signal.",
    },
    "USSLIND": {
        "name": "Leading Economic Index",
        "short_name": "LEI",
        "description": "Conference Board Leading Economic Index — MoM % change in composite of 10 leading indicators",
        "units": "MoM % Change",
        "category": "labor",
        "filename": "leading_economic_index.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (0.0, None), "yellow": (-0.5, 0.0), "red": (None, -0.5)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "FRED USSLIND is the MoM % change of the Conference Board LEI. Negative monthly readings signal deterioration; –0.5% MoM is a sharp contractionary drop consistent with pre-recession deterioration.",
        "predictive_reliability": 0.85,
        "revision_risk": "medium",
        "show_in_summary": True,
        "notes": "Monthly percent change in the Conference Board LEI. Persistent negative MoM readings have preceded every US recession since 1960.",
    },
    "CFNAI": {
        "name": "Chicago Fed National Activity Index",
        "short_name": "CFNAI",
        "description": "Chicago Fed National Activity Index — monthly composite of 85 indicators; 0 = trend growth, negative = below-trend",
        "units": "Index (standardized)",
        "category": "labor",
        "filename": "cfnai_activity.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (0.0, None), "yellow": (-0.7, 0.0), "red": (None, -0.7)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "CFNAI below –0.7 has reliably indicated below-trend growth; below –1.5 is consistent with recession onset (Chicago Fed guidance).",
        "predictive_reliability": 0.80,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Composite of 85 monthly indicators. Below –0.7 = below-trend growth; three consecutive months below –0.7 = strong recession signal.",
    },
    # ── Liquidity & Funding Stress ─────────────────────────────────────────
    "STLFSI4": {
        "name": "Financial Stress Index (St. Louis Fed)",
        "short_name": "FSI",
        "description": "St. Louis Fed Financial Stress Index — measures degree of financial stress in markets",
        "units": "Index",
        "category": "liquidity_stress",
        "filename": "stlfsi4.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 1.5), "red": (1.5, None)},
        "higher_is_bad": True,
        "normalization_method": "standardized_index",
        "calibration_window_years": 20,
        "threshold_rationale": "Index centered at 0 (mean conditions since 1993); +1.5 ≈ 90th percentile of tightening episodes, representing significant systemic stress.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "notes": "Index centered at 0. Negative = below-average stress; positive = above-average. Readings above 1.5 indicate significant systemic stress.",
    },
    "DCPF3M": {
        "name": "3-Month AA Financial CP Rate",
        "short_name": "3M CP Rate",
        "description": "3-Month AA Financial Commercial Paper Rate (Discount Basis) — short-term unsecured bank borrowing cost",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "cp_3m_financial.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.5), "yellow": (5.5, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Supporting series for CP-Treasury spread; absolute level driven by policy rate + credit premium — spread vs. Treasuries is the actionable signal.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Supporting series for CP-Treasury spread. Raw level reflects both policy rate and credit premium.",
    },
    "DGS3MO": {
        "name": "3-Month Treasury Rate",
        "short_name": "3M Treasury",
        "description": "3-Month Treasury Constant Maturity Rate — the short-term risk-free benchmark",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "treasury_3m.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.5), "yellow": (5.5, 7.0), "red": (7.0, None)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Short-term risk-free rate; levels reflect Fed policy stance. Used primarily as CP-Treasury spread denominator — standalone level is policy-cycle dependent.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Supporting series for CP-Treasury spread computation.",
    },
    "SOFR": {
        "name": "Secured Overnight Financing Rate",
        "short_name": "SOFR",
        "description": "Secured Overnight Financing Rate — daily rate for overnight Treasury-collateralized repo transactions",
        "units": "Percent",
        "category": "liquidity_stress",
        "filename": "sofr_rate.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "No standalone stress thresholds; LIBOR replacement tracks Fed Funds rate. Dislocations vs. FEDFUNDS signal repo funding stress.",
        "predictive_reliability": 0.60,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "LIBOR replacement rate since 2022. In isolation tracks Fed Funds rate; dislocations vs FEDFUNDS signal repo funding stress.",
    },
    "RRPONTSYD": {
        "name": "Fed Overnight Reverse Repo (RRP)",
        "short_name": "Reverse Repo",
        "description": "Overnight Reverse Repurchase Agreements: Treasury Securities Sold by Federal Reserve in Billions",
        "units": "Billions of Dollars",
        "category": "liquidity_stress",
        "filename": "rrp_usage.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (500, None), "yellow": (100, 500), "red": (None, 100)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Calibrated against the 2019 reserve-scarcity episode where repo rate spikes followed RRP near-depletion. Single-episode calibration: RRP drawdown can also reflect reserve redistribution or T-bill issuance absorbing MMF demand — not a universal rule.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "notes": "Usage of the Fed's overnight RRP facility. High levels indicate ample reserves parked at the Fed. Drawdown toward zero reduces a buffer against repo market stress but can also reflect benign reserve redistribution or money market fund reallocation to T-bills.",
    },
    # ── Credit Market Functionality ────────────────────────────────────────
    "BAMLH0A0HYM2": {
        "name": "High Yield OAS (ICE BofA)",
        "short_name": "HY Spread",
        "description": "ICE BofA US High Yield Index Option-Adjusted Spread — credit risk premium demanded by HY bond market",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "hy_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 4.0), "yellow": (4.0, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1997 ICE BofA dataset; ~4% ≈ 75th percentile, ~7% ≈ 90th percentile of full-cycle distribution.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "notes": "Credit spread in percent (400 bps = 4.0%). Pre-crisis normal: 3-4%. Persistent widening above 400 bps signals refinancing stress; above 700 bps indicates systemic credit deterioration.",
    },
    "BAA10Y": {
        "name": "Baa Corporate Bond Spread (Moody's)",
        "short_name": "Baa Spread",
        "description": "Moody's Seasoned Baa Corporate Bond Yield Relative to Yield on 10-Year Treasury Note — investment-grade credit risk premium",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "baa_10y_spread.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.0), "yellow": (2.0, 3.5), "red": (3.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Historical average ~2.0%; spikes to 3.5%+ during financial stress (2002, 2009, 2020). Available monthly from 1986.",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "Investment-grade credit spread proxy. Freely available from FRED since 1986, unlike the licensed ICE BofA HY series.",
    },
    "CP": {
        "name": "Corporate Profits (NIPA)",
        "short_name": "Corp. Profits",
        "description": "Corporate Profits with Inventory Valuation and Capital Consumption Adjustments (Quarterly SAAR, Billions of Dollars)",
        "units": "Billions of Dollars (SAAR)",
        "category": "labor",
        "filename": "corporate_profits.csv",
        "frequency": "Quarterly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (3, None), "yellow": (-5, 3), "red": (None, -5)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "YoY profit growth below -5% has been consistent with recession onset; the level relative to GDP (profit margin) shows whether CAPE is inflated by above-trend margins.",
        "predictive_reliability": 0.65,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Used to compute corporate profit margins (% of GDP). Above-average margins (>12% of GDP) mean CAPE is elevated partly by high earnings, not just high prices.",
    },
    "DRCCLACBS": {
        "name": "Credit Card Loan Delinquency Rate",
        "short_name": "CC Delinquency",
        "description": "Delinquency Rate on Credit Card Loans at All Commercial Banks",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "cc_delinquency_rate.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 3.0), "yellow": (3.0, 5.0), "red": (5.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1991 distribution; consumer credit health is a lagging indicator — rises after income stress is established. Peaked at ~6.8% in 2009.",
        "predictive_reliability": 0.70,
        "revision_risk": "low",
        "notes": "Quarterly H.8 release. Measures consumer credit health; peaked at ~6.8% in 2009. More timely within quarter than CRE data.",
    },
    "BAMLC0A0CM": {
        "name": "Investment Grade OAS (ICE BofA)",
        "short_name": "IG Spread",
        "description": "ICE BofA US Corporate Master Option-Adjusted Spread — investment grade credit premium",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "ig_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.5), "yellow": (1.5, 2.5), "red": (2.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1997 ICE BofA dataset; widening above 2.5% signals credit tightening reaching investment-grade issuers — a systemic stress indicator.",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "IG corporate spread in percent. Normal range: 0.8-1.5%. Widening above 2.5% signals credit tightening reaching investment-grade issuers.",
    },
    # ── Policy Constraints ─────────────────────────────────────────────────
    "WALCL": {
        "name": "Fed Balance Sheet (Total Assets)",
        "short_name": "Fed Assets",
        "description": "Federal Reserve: Total Assets (Less Eliminations from Consolidation), Wednesday Level",
        "units": "Millions of Dollars",
        "category": "policy_flex",
        "filename": "fed_balance_sheet.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "No stress thresholds — balance sheet size has no universal threshold; displayed as % of GDP for comparability across QE/QT cycles.",
        "predictive_reliability": 0.50,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Fed balance sheet size in millions. Tracks QE expansion and QT reduction. Context indicator — no simple threshold; shown as % of GDP for comparability.",
    },
    "FEDFUNDS": {
        "name": "Federal Funds Effective Rate",
        "short_name": "Fed Funds",
        "description": "Federal Funds Effective Rate — overnight interbank lending rate set by FOMC",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "fed_funds_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "No standalone stress thresholds; the real rate (FEDFUNDS – Core CPI) is the relevant policy-stance metric, not the nominal level.",
        "predictive_reliability": 0.70,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "The policy rate. High nominal rates are not inherently bad; the real rate (FEDFUNDS minus core CPI) is more informative for evaluating policy stance.",
    },
    "T5YIE": {
        "name": "5-Year Breakeven Inflation Rate",
        "short_name": "5Y BEI",
        "description": "5-Year Breakeven Inflation Rate — market-implied 5-year average inflation expectations",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "inflation_exp_5y.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 3.2), "red": (3.2, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "2.5% = Fed target + 50bp buffer (green/yellow boundary); 3.2%+ = unanchoring territory constraining the Fed's ability to ease (Bernanke/Yellen framework).",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "Derived from TIPS breakevens. Persistent readings above 3% signal inflation expectations unanchoring, which constrains the Fed's ability to ease policy.",
    },
    "T10YIE": {
        "name": "10-Year Breakeven Inflation Rate",
        "short_name": "10Y BEI",
        "description": "10-Year Breakeven Inflation Rate — market-implied long-run inflation expectations",
        "units": "Percent",
        "category": "policy_flex",
        "filename": "inflation_exp_10y.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 3.0), "red": (3.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Long-run expectations above 3% would represent significant unanchoring not seen since the 1980s — severely constraining Fed's ability to respond to economic weakness.",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "Long-run inflation expectations from TIPS market. Unanchoring above 3% would severely constrain the Fed's ability to respond to economic weakness.",
    },
    # ── Fiscal Maneuverability (raw components — not shown as standalone KPIs) ──
    "A091RC1Q027SBEA": {
        "name": "Federal Interest Payments",
        "short_name": "Interest Pmts",
        "description": "Government, Federal: Interest Payments (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "policy_flex",
        "filename": "federal_interest_payments.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Supporting data for interest/receipts ratio; no standalone threshold scoring.",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Numerator for debt service burden ratio. Combined with W006RC1Q027SBEA to yield interest/receipts %.",
    },
    "W006RC1Q027SBEA": {
        "name": "Federal Current Receipts",
        "short_name": "Fed Receipts",
        "description": "Government, Federal: Current Receipts (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "policy_flex",
        "filename": "federal_current_receipts.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Supporting data for interest/receipts ratio denominator; no standalone threshold scoring.",
        "predictive_reliability": 0.50,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Denominator for debt service burden ratio.",
    },
    "GDP": {
        "name": "Nominal GDP",
        "short_name": "GDP",
        "description": "Gross Domestic Product, Nominal (Quarterly, SAAR, Billions)",
        "units": "Billions of Dollars",
        "category": "fiscal",
        "filename": "nominal_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Denominator for GDP-ratio calculations; no standalone stress threshold.",
        "predictive_reliability": 0.50,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Nominal GDP for computing balance sheet % of GDP and similar ratios.",
    },
    # ── Financial Conditions Index ─────────────────────────────────────────
    "NFCI": {
        "name": "National Financial Conditions Index",
        "short_name": "NFCI",
        "description": "Chicago Fed National Financial Conditions Index — weekly measure of U.S. financial conditions",
        "units": "Index",
        "category": "liquidity_stress",
        "filename": "nfci.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 0.7), "red": (0.7, None)},
        "higher_is_bad": True,
        "normalization_method": "standardized_index",
        "calibration_window_years": 20,
        "threshold_rationale": "Chicago Fed constructs the index with mean 0 (1971 base); +0.7 ≈ 90th percentile of tightening episodes. Combines 105 indicators across risk, credit, and leverage subindices.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "notes": "Index centered at 0 (average conditions, 1971 onward). Positive = tighter than average; negative = looser. Combines 105 financial indicators across risk, credit, and leverage.",
    },
    "NFCICREDIT": {
        "name": "NFCI Credit Subindex",
        "short_name": "NFCI Credit",
        "description": "Chicago Fed NFCI: Credit Subindex — measures tightness of credit conditions specifically",
        "units": "Index",
        "category": "credit_markets",
        "filename": "nfci_credit.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 0.0), "yellow": (0.0, 0.7), "red": (0.7, None)},
        "higher_is_bad": True,
        "normalization_method": "standardized_index",
        "calibration_window_years": 20,
        "threshold_rationale": "Credit-specific subindex of NFCI; same mean-0 construction. Isolates credit channel stress from leverage and risk components.",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "notes": "Credit-specific sub-index of NFCI. Isolates the credit channel from broader financial conditions.",
    },
    # ── Yield Curve ───────────────────────────────────────────────────────
    "T10Y2Y": {
        "name": "Yield Curve Spread (10Y − 2Y)",
        "short_name": "Yield Curve",
        "description": "10-Year Treasury Yield minus 2-Year Treasury Yield",
        "units": "Percent",
        "category": "rates",
        "filename": "yield_curve_spread.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (0.5, None), "yellow": (0.0, 0.5), "red": (None, 0.0)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Estrella & Mishkin (1998): inversion precedes every US recession since 1970. Thresholds: <0% = inverted (red), 0–0.5% = flat (yellow), >0.5% = normal slope (green).",
        "predictive_reliability": 0.85,
        "revision_risk": "low",
        "notes": "Inverted curve (negative) has preceded every US recession since 1970. Green = normal slope; yellow = flat; red = inverted.",
    },
    # ── Bank Lending Standards ─────────────────────────────────────────────
    "DRTSCILM": {
        "name": "Bank Lending Standards (C&I Loans)",
        "short_name": "Lending Stds",
        "description": "Net % of Domestic Banks Tightening Standards for C&I Loans, Large & Medium Firms",
        "units": "Percent (Net)",
        "category": "credit_markets",
        "filename": "bank_lending_standards.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 10), "yellow": (10, 40), "red": (40, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Bernanke & Lown (1991): >40% net tightening historically precedes C&I credit contraction by 2–4 quarters. SLOOS survey with quarterly frequency.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "notes": "SLOOS survey. Positive = net tightening; negative = net loosening. Tightening above 40% has historically preceded credit contractions.",
    },
    # ── Recession Probability ──────────────────────────────────────────────
    "RECPROUSM156N": {
        "name": "Recession Probability (NY Fed, 12-Month)",
        "short_name": "Rec. Probability",
        "description": "NY Fed Probability of US Recession Predicted by Treasury Spread, 12 Months Ahead",
        "units": "Percent",
        "category": "financial_stress",
        "filename": "recession_probability.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 15), "yellow": (15, 40), "red": (40, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Estrella & Mishkin (1998) NY Fed probit model: >30–40% 12-month probability has historically been a reliable recession signal. Uses 10Y–3M spread as input.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "notes": "NY Fed probit model using the 3-month / 10-year yield spread. Readings above 30% have historically been reliable recession signals.",
    },
    # ── Housing ───────────────────────────────────────────────────────────
    "MORTGAGE30US": {
        "name": "30-Year Fixed Mortgage Rate",
        "short_name": "Mortgage Rate",
        "description": "30-Year Fixed Rate Mortgage Average in the United States (Freddie Mac PMMS)",
        "units": "Percent",
        "category": "housing",
        "filename": "mortgage_rate_30y.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 5.0), "yellow": (5.0, 7.0), "red": (7.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1990 distribution; affordability-adjusted threshold varies with home price levels — percentile scoring captures current rate-cycle context.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "notes": "Primary Mortgage Market Survey. Higher rates directly reduce housing affordability and suppress transaction volume and starts.",
    },
    "HOUST": {
        "name": "Housing Starts (Total)",
        "short_name": "Housing Starts",
        "description": "Housing Starts: Total New Privately Owned Housing Units Started, SAAR",
        "units": "Thousands of Units",
        "category": "housing",
        "filename": "housing_starts.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (1300, None), "yellow": (900, 1300), "red": (None, 900)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1990 distribution; very sensitive to mortgage rate cycles. Fixed floor of 900K represents structural contraction consistent with prior recessions.",
        "predictive_reliability": 0.65,
        "revision_risk": "medium",
        "notes": "Leading indicator for construction employment and materials demand. Very sensitive to mortgage rates.",
    },
    "CSUSHPINSA": {
        "name": "Case-Shiller Home Price Index",
        "short_name": "Home Prices",
        "description": "S&P CoreLogic Case-Shiller U.S. National Home Price Index (NSA)",
        "units": "Index (Jan 2000 = 100)",
        "category": "housing",
        "filename": "case_shiller_hpi.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 YoY distribution; >8% YoY signals affordability stress and speculative dynamics consistent with past boom-bust episodes.",
        "predictive_reliability": 0.60,
        "revision_risk": "low",
        "notes": "3-month smoothed repeat-sales index. Published with ~2-month lag. YoY above 8% signals affordability stress.",
    },
    # ── Dollar ────────────────────────────────────────────────────────────
    "DTWEXBGS": {
        "name": "Broad U.S. Dollar Index",
        "short_name": "Dollar Index",
        "description": "Nominal Broad U.S. Dollar Index (Goods, Trade-Weighted vs. 26 major currencies)",
        "units": "Index (Jan 2006 = 100)",
        "category": "markets",
        "filename": "dollar_index.csv",
        "frequency": "Weekly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 8), "yellow": (8, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 distribution; rapid appreciation (>8% YoY) tightens global financial conditions, pressures EM debt, and weighs on US multinationals.",
        "predictive_reliability": 0.60,
        "revision_risk": "low",
        "notes": "Broad trade-weighted dollar. Rapid appreciation (>8% YoY) tightens global financial conditions, pressures EM debt, and weighs on US multinationals.",
    },
    # ── Leading Indicator Components (BCI) ────────────────────────────────
    "PERMIT": {
        "name": "Building Permits (New Private Housing)",
        "short_name": "Building Permits",
        "description": "New Privately-Owned Housing Units Authorized in Permit-Issuing Places, SAAR",
        "units": "Thousands of Units",
        "category": "housing",
        "filename": "building_permits.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (0, None), "yellow": (-15, 0), "red": (None, -15)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1990 YoY distribution; leading indicator for residential construction and related employment. Sustained YoY contraction precedes housing-sector recessions.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "BCI leading indicator component. YoY contraction signals slowing construction pipeline and forward employment weakness.",
    },
    "AMTMNO": {
        "name": "Mfg New Orders: Total Manufacturing",
        "short_name": "Mfg New Orders",
        "description": "Manufacturers' New Orders: Total Manufacturing (Monthly, SA, Millions of Dollars)",
        "units": "Millions of Dollars",
        "category": "labor",
        "filename": "mfg_new_orders.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (5, None), "yellow": (0, 5), "red": (None, 0)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "YoY % change in total manufacturing orders. Below 0% = contraction in order flow; sustained declines typically precede payroll contraction by 2-4 months.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "BCI leading indicator component (Census Bureau). YoY contraction in manufacturing orders leads broad economic slowdowns.",
    },
    "AWHAETP": {
        "name": "Avg Weekly Hours: Total Private",
        "short_name": "Avg Weekly Hours",
        "description": "Average Weekly Hours of All Employees: Total Private (SA)",
        "units": "Hours",
        "category": "labor",
        "filename": "avg_weekly_hours.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (34.5, None), "yellow": (34.0, 34.5), "red": (None, 34.0)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Employers cut hours before cutting headcount; this series is included in the Conference Board LEI. Percentile vs. post-1990 distribution captures the secular trend.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Conference Board LEI component. Declining hours precede payroll contractions by 1-2 months on average.",
    },
    "T10Y3M": {
        "name": "Yield Curve Spread (10Y − 3M)",
        "short_name": "10Y-3M Spread",
        "description": "10-Year Treasury Yield minus 3-Month Treasury Bill Yield",
        "units": "Percent",
        "category": "rates",
        "filename": "yield_spread_10y3m.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (0.5, None), "yellow": (0.0, 0.5), "red": (None, 0.0)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Estrella & Mishkin (1998): the 10Y-3M spread is the yield curve specification in the NY Fed recession model. Inversion (negative) has preceded every post-1970 recession.",
        "predictive_reliability": 0.85,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "NY Fed recession model input. Inversion has preceded every US recession since 1968 with a 6-18 month lead.",
    },
    "TEMPHELPS": {
        "name": "Temporary Help Services Employment",
        "short_name": "Temp Employment",
        "description": "All Employees: Professional and Business Services: Temporary Help Services (Seasonally Adjusted)",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "temp_employment.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (0, None), "yellow": (-5, 0), "red": (None, -5)},
        "higher_is_bad": False,
        "normalization_method": "zscore",
        "calibration_window_years": 20,
        "threshold_rationale": "Z-score vs 20-year YoY distribution; companies reduce temp headcount 3–6 months before cutting permanent staff — a reliable early-cycle deterioration signal.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "BCI leading indicator component. Temp employment leads the employment cycle by 3–6 months; sustained YoY decline historically precedes nonfarm payroll contraction.",
    },
    # ── Extended Labor Market ──────────────────────────────────────────────
    "CES0500000003": {
        "name": "Average Hourly Earnings",
        "short_name": "Avg Hourly Earnings",
        "description": "Average Hourly Earnings of All Employees: Total Private (Seasonally Adjusted)",
        "units": "Dollars per Hour",
        "category": "labor",
        "filename": "avg_hourly_earnings.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 4.0), "yellow": (4.0, 5.5), "red": (5.5, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "YoY wage growth >4% exceeds Fed comfort zone for 2% PCE target given ~2% productivity growth; >5.5% historically correlated with entrenched inflation.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Primary monthly wage gauge. YoY growth above productivity trend signals inflationary pressure.",
    },
    "ECIALLCIV": {
        "name": "Employment Cost Index — All Civilian",
        "short_name": "ECI All Civilian",
        "description": "Employment Cost Index: Total Compensation, All Civilian Workers (Quarterly, SA)",
        "units": "Index (Dec 2005=100)",
        "category": "labor",
        "filename": "eci_all_civilian.csv",
        "frequency": "Quarterly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 3.5), "yellow": (3.5, 5.0), "red": (5.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "ECI is the Fed's preferred wage measure: less volatile than AHE. Growth above 3.5% YoY is inconsistent with 2% inflation. No revision risk (employer survey).",
        "predictive_reliability": 0.75,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Quarterly BLS employer survey — lower revision risk than AHE. Fed explicitly cites ECI in FOMC minutes.",
    },
    "JTSJOL": {
        "name": "JOLTS Job Openings",
        "short_name": "Job Openings",
        "description": "Job Openings: Total Nonfarm (Seasonally Adjusted, Thousands)",
        "units": "Thousands",
        "category": "labor",
        "filename": "jolts_openings.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (8000, None), "yellow": (6000, 8000), "red": (None, 6000)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2001 JOLTS history; <6M openings signals cooling labor demand. Beveridge curve: openings relative to unemployment diagnoses slack vs. mismatch.",
        "predictive_reliability": 0.75,
        "revision_risk": "high",
        "show_in_summary": False,
        "notes": "Leads payroll changes by 2–4 months. Openings/unemployed ratio (V/U ratio) is a key Fed labor market tightness gauge.",
    },
    "JTSQUR": {
        "name": "JOLTS Quits Rate",
        "short_name": "Quits Rate",
        "description": "Job Openings: Quits Rate: Total Nonfarm (Seasonally Adjusted, Percent)",
        "units": "Percent",
        "category": "labor",
        "filename": "jolts_quits_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (2.5, None), "yellow": (1.8, 2.5), "red": (None, 1.8)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2001 JOLTS history; quits rate below 2% signals workers losing confidence in job mobility — characteristic of labor market turning points.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Workers quit voluntarily only when confident they can find better work. Sharp drops lead unemployment by 3–6 months.",
    },
    "JTSLDR": {
        "name": "JOLTS Layoffs Rate",
        "short_name": "Layoffs Rate",
        "description": "Layoffs and Discharges Rate: Total Nonfarm (Seasonally Adjusted, Percent)",
        "units": "Percent",
        "category": "labor",
        "filename": "jolts_layoffs_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.2), "yellow": (1.2, 1.8), "red": (1.8, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2001 JOLTS history; layoffs rate >1.5% historically coincides with or precedes rising unemployment claims.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Rising layoffs rate leads initial claims and unemployment rate by 1–3 months.",
    },
    "U6RATE": {
        "name": "U-6 Unemployment Rate",
        "short_name": "U-6 Rate",
        "description": "Total Unemployed, Plus All Marginally Attached Workers Plus Total Employed Part-Time for Economic Reasons",
        "units": "Percent",
        "category": "labor",
        "filename": "u6_unemployment.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 8.0), "yellow": (8.0, 11.0), "red": (11.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-1994 distribution (first year available). U6-U3 gap measures labor market slack beyond headline unemployment; widening gap signals hidden underemployment.",
        "predictive_reliability": 0.80,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Broadest BLS unemployment measure. U6-U3 spread widens when marginal workers are excluded from U3; critical for measuring true slack.",
    },
    "CCSA": {
        "name": "Continued Jobless Claims",
        "short_name": "Cont. Claims",
        "description": "Continued Claims (Insured Unemployment), Seasonally Adjusted",
        "units": "Thousands of Persons",
        "category": "labor",
        "filename": "continued_claims.csv",
        "frequency": "Weekly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1750), "yellow": (1750, 2200), "red": (2200, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. post-2000 distribution; persistent elevated claims signal employers are not rehiring laid-off workers. Lags initial claims by ~1 week.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Number of workers currently receiving unemployment benefits. Measures absorption rate — how quickly laid-off workers are rehired.",
    },
    "OPHNFB": {
        "name": "Nonfarm Business Productivity",
        "short_name": "Productivity",
        "description": "Nonfarm Business Sector: Real Output Per Hour of All Persons (Seasonally Adjusted, Index 2017=100)",
        "units": "Index (2017=100)",
        "category": "labor",
        "filename": "nonfarm_productivity.csv",
        "frequency": "Quarterly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (1.5, None), "yellow": (0, 1.5), "red": (None, 0)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Long-run productivity growth of ~1.5% YoY justifies non-inflationary wage gains above that level. Negative productivity signals unit labor costs rising unsustainably.",
        "predictive_reliability": 0.65,
        "revision_risk": "high",
        "show_in_summary": False,
        "notes": "Key to non-inflationary growth: wage growth sustainable only if matched by productivity. High revision risk — initial estimates routinely revised ±1pp.",
    },
    "ULCNFB": {
        "name": "Unit Labor Costs — Nonfarm",
        "short_name": "Unit Labor Costs",
        "description": "Nonfarm Business Sector: Unit Labor Costs for All Persons (Seasonally Adjusted, Index 2017=100)",
        "units": "Index (2017=100)",
        "category": "labor",
        "filename": "unit_labor_costs.csv",
        "frequency": "Quarterly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "ULC > 2.5% YoY signals wages outpacing productivity — inflationary pressure that firms pass through to prices. ULC is the transmission mechanism from labor costs to goods/services prices.",
        "predictive_reliability": 0.70,
        "revision_risk": "high",
        "show_in_summary": False,
        "notes": "= Compensation / Productivity. Rising ULC compresses margins or passes through to prices. Key Fed inflation input.",
    },
    # ── Extended Inflation ─────────────────────────────────────────────────
    "MEDCPIM158SFRBCLE": {
        "name": "Median CPI (Cleveland Fed)",
        "short_name": "Median CPI",
        "description": "Median Consumer Price Index (12-Month Percent Change, Cleveland Fed)",
        "units": "Percent Change",
        "category": "inflation",
        "filename": "median_cpi.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Median CPI strips extreme price movements by using the median of component price changes. It is the best predictor of future inflation in academic literature (Stock & Watson).",
        "predictive_reliability": 0.85,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Median component of CPI distribution — best predictor of future core PCE. Released with CPI each month by Cleveland Fed.",
    },
    "PCETRIM12M159SFRBDAL": {
        "name": "Trimmed Mean PCE (Dallas Fed)",
        "short_name": "Trimmed Mean PCE",
        "description": "Trimmed Mean PCE Inflation Rate, 12-Month (Dallas Fed)",
        "units": "Percent Change",
        "category": "inflation",
        "filename": "trimmed_mean_pce.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Trimmed mean removes the top and bottom 31% of price changes by expenditure weight. Broadly comparable to median CPI in predictive power for underlying inflation.",
        "predictive_reliability": 0.82,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Dallas Fed's preferred alternative to core PCE. Trims the tails of the monthly price distribution. Highly correlated with median CPI.",
    },
    "CPILFENS": {
        "name": "CPI Supercore (ex Food/Energy/Shelter)",
        "short_name": "Supercore CPI",
        "description": "CPI: All Items Less Food, Energy, and Shelter (Not Seasonally Adjusted)",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_supercore.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Supercore strips the most volatile and persistent components. Fed Chair Powell cited supercore services (PCE equivalent) as the primary inflation measure during 2022–2023.",
        "predictive_reliability": 0.78,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "CPI less food, energy, and shelter — isolates cyclical services inflation driven by labor costs and demand. Conceptually equivalent to Fed's 'supercore' PCE watch.",
    },
    "CUSR0000SEHC": {
        "name": "CPI: Owners' Equivalent Rent",
        "short_name": "OER",
        "description": "CPI: Owners' Equivalent Rent of Residences (Not Seasonally Adjusted)",
        "units": "Index (1982–84=100)",
        "category": "inflation",
        "filename": "cpi_oer.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 3.0), "yellow": (3.0, 5.0), "red": (5.0, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "OER is the largest single CPI component (~26% weight) and lags actual rents by 12–18 months. Disinflation in spot rents takes over a year to appear in CPI.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Largest CPI component. Imputed from market rents with an 12–18 month lag. Key driver of core CPI persistence above target.",
    },
    "MICH": {
        "name": "U-Mich 1-Yr Inflation Expectations",
        "short_name": "Inflation Exp (1Y)",
        "description": "University of Michigan: Inflation Expectation — Median Next 12 Months",
        "units": "Percent",
        "category": "inflation",
        "filename": "mich_inflation_exp.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 3.0), "yellow": (3.0, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Historically ~3% mean; elevated expectations risk becoming self-fulfilling. Fed tracks 'deanchoring' risk — expectations persistently above 4% signal credibility erosion.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Consumer survey — more volatile than market-based measures but captures household psychology important to wage demands.",
    },
    "CORESTICKM159SFRBATL": {
        "name": "Sticky Price CPI (Atlanta Fed)",
        "short_name": "Sticky CPI",
        "description": "Sticky Price Consumer Price Index Less Food and Energy (12-Month % Change, Atlanta Fed)",
        "units": "Percent Change",
        "category": "inflation",
        "filename": "sticky_cpi.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 3.0), "yellow": (3.0, 4.5), "red": (4.5, None)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Sticky prices (rents, medical, education) change infrequently, so their movement signals fundamental inflationary regime shifts rather than temporary supply shocks.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Components that change price infrequently (sticky) vs frequently (flexible). Sticky prices are the best predictor of persistent inflation.",
    },
    # ── Banking & Credit Stress ────────────────────────────────────────────
    "DRALACBN": {
        "name": "Loan Delinquency Rate — All",
        "short_name": "Delinquency (All)",
        "description": "Delinquency Rate on All Loans and Leases, All Commercial Banks (Seasonally Adjusted)",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "delinquency_all_loans.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.5), "yellow": (1.5, 2.5), "red": (2.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 25,
        "threshold_rationale": "Percentile vs. post-1990 history; >2.5% has preceded systemic credit events. Rapid 6-month increase matters as much as level.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Comprehensive bank credit quality gauge. Rising rapidly signals deteriorating borrower quality.",
    },
    "DRCLACBS": {
        "name": "CRE Loan Delinquency Rate",
        "short_name": "CRE Delinquency",
        "description": "Delinquency Rate on Commercial Real Estate Loans, All Commercial Banks (Seasonally Adjusted)",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "delinquency_cre.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.0), "yellow": (1.0, 2.5), "red": (2.5, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 25,
        "threshold_rationale": "CRE concentrated at regional banks; >2.5% historically preceded regional banking stress episodes (S&L crisis, GFC). Office/retail vacancy surge is a 2024-onwards risk.",
        "predictive_reliability": 0.80,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "CRE delinquencies are concentrated at small/mid-size banks. Rising sharply in office and retail segments post-COVID.",
    },
    "DRSFRMACBS": {
        "name": "Residential Mortgage Delinquency Rate",
        "short_name": "Mortgage Delinquency",
        "description": "Delinquency Rate on Single-Family Residential Mortgages, All Commercial Banks (Seasonally Adjusted)",
        "units": "Percent",
        "category": "credit_markets",
        "filename": "delinquency_mortgage.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.5), "yellow": (1.5, 3.0), "red": (3.0, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 25,
        "threshold_rationale": "Percentile vs. post-1991 history. Mortgage delinquencies >3% (GFC reached 11%) typically require systemic government response. Rising from low base warrants monitoring.",
        "predictive_reliability": 0.75,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Consumer stress gauge — rising mortgage delinquencies signal household balance sheet pressure.",
    },
    "DPSACBM027SBOG": {
        "name": "Bank Deposits (All Commercial Banks)",
        "short_name": "Bank Deposits",
        "description": "Deposits, All Commercial Banks (Seasonally Adjusted, Billions of Dollars)",
        "units": "Billions of Dollars",
        "category": "credit_markets",
        "filename": "bank_deposits.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (0, None), "yellow": (-3, 0), "red": (None, -3)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Deposit outflows are a direct banking stress indicator. YoY contraction >3% signals systemic deposit flight risk. SVB 2023 highlighted speed of modern bank runs.",
        "predictive_reliability": 0.70,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "System-wide deposit stability measure. Rapid YoY contraction signals tightening monetary conditions or bank stress. SVB 2023: regional bank deposits fell sharply before failure.",
    },
    # ── Global Macro — Commodities ────────────────────────────────────────
    "DCOILBRENTEU": {
        "name": "Brent Crude Oil Price",
        "short_name": "Brent Crude",
        "description": "Crude Oil Prices: Brent - Europe (Dollars per Barrel)",
        "units": "USD per Barrel",
        "category": "global_macro",
        "filename": "brent_crude.csv",
        "frequency": "Daily",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 20), "yellow": (20, 50), "red": (50, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Percentile vs. 20Y history. >50% YoY surge historically transmits to headline CPI within 3–6 months. Rapid declines signal demand destruction.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Key commodity price; high correlation with headline CPI via gasoline and transportation costs.",
    },
    "PPIACO": {
        "name": "PPI: All Commodities",
        "short_name": "PPI Commodities",
        "description": "Producer Price Index by Commodity: All Commodities (Monthly Index)",
        "units": "Index (1982=100)",
        "category": "global_macro",
        "filename": "ppi_all_commodities.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 5), "yellow": (5, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 30,
        "threshold_rationale": "Percentile vs. 30Y history. PPI leads CPI by ~2-3 months. >15% YoY sustained = significant inflation pass-through risk.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Broad commodity index; leads consumer prices. Supply shocks visible before appearing in CPI.",
    },
    "GOLDPMGBD228NLBMA": {
        "name": "Gold Price (London PM Fix)",
        "short_name": "Gold Price",
        "description": "Gold Fixing Price 3:00 P.M. (London Bullion Market) in USD per Troy Ounce",
        "units": "USD per Troy Ounce",
        "category": "global_macro",
        "filename": "gold_price.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 10), "yellow": (10, 25), "red": (25, None)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 25,
        "threshold_rationale": "Gold YoY > 25% historically signals elevated safe-haven demand, inflation fear, or USD stress. The signal is context-dependent.",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Safe-haven demand indicator. Rising gold often signals inflation fear, geopolitical stress, or loss of confidence in fiat stability.",
    },
    # ── Global Macro — FX ────────────────────────────────────────────────
    "DEXUSEU": {
        "name": "USD/EUR Exchange Rate",
        "short_name": "EUR/USD",
        "description": "U.S. Dollars per Euro (Daily)",
        "units": "USD per EUR",
        "category": "global_macro",
        "filename": "fx_eur_usd.csv",
        "frequency": "Daily",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (-5, 5), "yellow": (-10, -5), "red": (None, -10)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Rapid EUR/USD decline (>10% YoY) = sharp dollar strengthening = global financial tightening impulse.",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Largest FX pair globally. Sharp USD appreciation tightens dollar-denominated funding conditions worldwide.",
    },
    "DEXJPUS": {
        "name": "JPY/USD Exchange Rate",
        "short_name": "JPY/USD",
        "description": "Japanese Yen per U.S. Dollar (Daily)",
        "units": "JPY per USD",
        "category": "global_macro",
        "filename": "fx_jpy_usd.csv",
        "frequency": "Daily",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 5), "yellow": (5, 15), "red": (15, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Rising JPY/USD = yen depreciation = BOJ/Fed policy divergence. >15% YoY yen weakening signals BoJ yield curve control stress.",
        "predictive_reliability": 0.50,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Key carry trade currency. Yen weakness = risk-on/carry trade expansion; sharp yen strength = carry unwind (global risk-off).",
    },
    "DEXCHUS": {
        "name": "CNY/USD Exchange Rate",
        "short_name": "CNY/USD",
        "description": "Chinese Yuan per U.S. Dollar (Daily)",
        "units": "CNY per USD",
        "category": "global_macro",
        "filename": "fx_cny_usd.csv",
        "frequency": "Daily",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (None, 3), "yellow": (3, 8), "red": (8, None)},
        "higher_is_bad": True,
        "normalization_method": "percentile",
        "calibration_window_years": 20,
        "threshold_rationale": "Yuan depreciation >8% YoY historically triggers global EM contagion and competitive devaluation fears.",
        "predictive_reliability": 0.55,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Managed currency but PBOC-driven moves have global implications. Rapid depreciation = China growth stress or capital outflows.",
    },
    # ── Global Macro — Central Bank Rates ────────────────────────────────
    "IR3TIB01EZM156N": {
        "name": "Euro Area 3-Month Interbank Rate",
        "short_name": "ECB Rate Proxy",
        "description": "3-Month or 90-Day Rates and Yields: Interbank Rates for Euro Area (Monthly, OECD) — ECB Policy Rate Proxy",
        "units": "Percent",
        "category": "global_macro",
        "filename": "ecb_policy_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 2.5), "yellow": (2.5, 4.0), "red": (4.0, None)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 25,
        "threshold_rationale": "ECB's own 2% inflation target implies neutral rates near 2–2.5%. Above 4% = historically restrictive for the eurozone.",
        "predictive_reliability": 0.60,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "ECB policy rate from OECD dataset. Fed-ECB divergence drives EUR/USD and cross-border capital flows.",
    },
    "IRSTCB01JPM156N": {
        "name": "BOJ Policy Rate",
        "short_name": "BOJ Rate",
        "description": "Immediate Rates: Less than 24 Hours: Central Bank Rates for Japan (Monthly, OECD)",
        "units": "Percent",
        "category": "global_macro",
        "filename": "boj_policy_rate.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {"green": (None, 1.0), "yellow": (1.0, 2.5), "red": (2.5, None)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 25,
        "threshold_rationale": "BOJ has operated near zero since 1999; any rate normalization above 1% signals a historic regime shift with global carry-trade implications.",
        "predictive_reliability": 0.60,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "BOJ normalization is a major global tail risk: yen carry unwind when BOJ hikes could trigger forced global asset sales.",
    },
    # ── Structural Macro — Output Gap & Demographics ──────────────────────
    "GDPC1": {
        "name": "Real GDP",
        "short_name": "Real GDP",
        "description": "Real Gross Domestic Product (Quarterly SAAR, Billions Chained 2017 Dollars)",
        "units": "Billions of Chained 2017 Dollars",
        "category": "structural",
        "filename": "real_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (2.0, None), "yellow": (0, 2.0), "red": (None, 0)},
        "higher_is_bad": False,
        "normalization_method": "percentile",
        "calibration_window_years": 30,
        "threshold_rationale": "Positive real GDP growth above 2% (trend) = green; below trend but positive = yellow; negative = red (recession signal).",
        "predictive_reliability": 0.85,
        "revision_risk": "high",
        "show_in_summary": False,
        "notes": "Used with GDPPOT to compute output gap. Subject to significant revision — advance estimate can shift by 1–2pp.",
    },
    "GDPPOT": {
        "name": "Real Potential GDP (CBO)",
        "short_name": "Potential GDP",
        "description": "Real Potential Gross Domestic Product (CBO, Quarterly, Billions Chained 2017 Dollars)",
        "units": "Billions of Chained 2017 Dollars",
        "category": "structural",
        "filename": "potential_gdp.csv",
        "frequency": "Quarterly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "CBO's estimate of the economy's non-inflationary production capacity. Used to compute the output gap; no standalone threshold.",
        "predictive_reliability": 0.70,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "CBO revises this annually. Positive output gap (GDP > potential) = overheating; negative = economic slack.",
    },
    "LFWA64TTUSM647S": {
        "name": "Working Age Population (15–64)",
        "short_name": "Working Age Pop.",
        "description": "Working Age Population: Aged 15-64: All Persons for the United States (Monthly, Thousands)",
        "units": "Thousands of Persons",
        "category": "structural",
        "filename": "working_age_population.csv",
        "frequency": "Monthly",
        "risk_basis": "yoy",
        "risk_thresholds": {"green": (0.5, None), "yellow": (0.2, 0.5), "red": (None, 0.2)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Growth below 0.2% YoY = significant demographic headwind for labor supply and potential GDP growth.",
        "predictive_reliability": 0.65,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Slow-moving structural labor supply driver. Aging demographics are the primary reason for declining US LFPR since 2000.",
    },
    "DFII10": {
        "name": "10-Year TIPS Yield (Real Rate)",
        "short_name": "10Y TIPS Yield",
        "description": "Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Inflation-Indexed (Daily, %)",
        "units": "Percent",
        "category": "structural",
        "filename": "tips_10y_yield.csv",
        "frequency": "Daily",
        "risk_basis": "level",
        "risk_thresholds": {"green": (-0.5, 1.5), "yellow": (1.5, 2.5), "red": (2.5, None)},
        "higher_is_bad": False,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "Real rates above 2.5% are historically restrictive — they compress equity multiples, slow housing, and pressure leveraged borrowers.",
        "predictive_reliability": 0.80,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Long-run real rate benchmark derived from inflation-protected bonds. ≠ r* (neutral rate): the TIPS yield also embeds a real term premium (~0.5–1.5%) and a TIPS liquidity discount not present in the neutral rate concept. Used as a policy-stance benchmark. Negative real rates = financial repression; very high real rates = significant growth headwind.",
    },
    # ── Fiscal Analytics ─────────────────────────────────────────────────
    "FYFSD": {
        "name": "Federal Surplus/Deficit (Annual FY)",
        "short_name": "Fed Deficit ($B)",
        "description": "Federal Surplus or Deficit [-] (Annual Fiscal Year, Billions of Dollars)",
        "units": "Billions of Dollars",
        "category": "fiscal",
        "filename": "federal_surplus_deficit.csv",
        "frequency": "Annual",
        "risk_basis": "level",
        "risk_thresholds": {"green": (-500, None), "yellow": (-1500, -500), "red": (None, -1500)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 30,
        "threshold_rationale": "Deficit below -$1.5T historically signals unsustainable fiscal trajectory absent growth acceleration. Nominal level context-dependent; use with % GDP.",
        "predictive_reliability": 0.55,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Annual fiscal year total. Combined with interest payments gives primary balance. Do not interpret in isolation from interest rates and growth.",
    },
    "FYFSGDA188S": {
        "name": "Federal Surplus/Deficit as % of GDP",
        "short_name": "Deficit % GDP",
        "description": "Federal Surplus or Deficit [-] as Percent of Gross Domestic Product (Annual, BEA NIPA)",
        "units": "Percent of GDP",
        "category": "fiscal",
        "filename": "federal_surplus_deficit_pct_gdp.csv",
        "frequency": "Annual",
        "risk_basis": "level",
        "risk_thresholds": {"green": (-3, None), "yellow": (-6, -3), "red": (None, -6)},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 40,
        "threshold_rationale": "EU Maastricht 3% threshold is widely used. Deficit >6% in non-recessionary periods historically unsustainable without monetization.",
        "predictive_reliability": 0.60,
        "revision_risk": "medium",
        "show_in_summary": False,
        "notes": "Used to compute fiscal impulse (YoY change) and compare to r-g dynamics for debt stabilization analysis.",
    },
    # ── Recession Reference (not shown as a KPI) ──────────────────────────
    "USREC": {
        "name": "NBER Recession Indicator",
        "short_name": "Recession",
        "description": "NBER Based Recession Indicators for the United States (1=Recession, 0=Expansion)",
        "units": "Binary",
        "category": "labor",
        "filename": "us_recession.csv",
        "frequency": "Monthly",
        "risk_basis": "level",
        "risk_thresholds": {},
        "higher_is_bad": True,
        "normalization_method": "fixed_thresholds",
        "calibration_window_years": 20,
        "threshold_rationale": "NBER ground truth classification; no threshold scoring. Used exclusively for recession shading on charts.",
        "predictive_reliability": 1.00,
        "revision_risk": "low",
        "show_in_summary": False,
        "notes": "Used exclusively for recession shading on charts.",
    },
}

# Display labels for each category group
CATEGORY_LABELS = {
    "inflation":       "Inflation & Prices",
    "money_supply":    "Money Supply",
    "markets":         "Markets",
    "rates":           "Interest Rates",
    "financial_stress":"Financial Stress",
    "fiscal":          "Fiscal Health",
    "labor":           "Labor Market",
    "valuation":       "Market Valuation",
    "housing":         "Housing Market",
    # System resilience categories
    "liquidity_stress": "Liquidity & Funding Stress",
    "credit_markets":   "Credit Market Functionality",
    "policy_flex":      "Policy Constraints",
    # Global & structural
    "global_macro":     "Global Macro & FX",
    "structural":       "Structural & Long-Run",
}

# Ordered list for display
CATEGORY_ORDER = [
    "inflation", "labor", "valuation", "markets", "rates",
    "financial_stress", "fiscal", "money_supply", "housing",
    "liquidity_stress", "credit_markets", "policy_flex",
    "global_macro", "structural",
]
